// Auto-generated by build.rs, DO NOT EDIT
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum BaseTerrain {
    Ocean,
    Coast,
    Grassland,
    Plain,
    Tundra,
    Desert,
    Lake,
    Snow,
}

impl BaseTerrain {
    pub fn as_str(&self) -> &'static str {
        match self {
            BaseTerrain::Ocean => "Ocean",
            BaseTerrain::Coast => "Coast",
            BaseTerrain::Grassland => "Grassland",
            BaseTerrain::Plain => "Plain",
            BaseTerrain::Tundra => "Tundra",
            BaseTerrain::Desert => "Desert",
            BaseTerrain::Lake => "Lake",
            BaseTerrain::Snow => "Snow",
        }
    }
}
