// Auto-generated by build.rs, DO NOT EDIT
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum CityStateType {
    Cultured,
    Maritime,
    Mercantile,
    Militaristic,
    Religious,
}

impl CityStateType {
    pub fn as_str(&self) -> &'static str {
        match self {
            CityStateType::Cultured => "Cultured",
            CityStateType::Maritime => "Maritime",
            CityStateType::Mercantile => "Mercantile",
            CityStateType::Militaristic => "Militaristic",
            CityStateType::Religious => "Religious",
        }
    }
}
