// Auto-generated by build.rs, DO NOT EDIT
use super::EnumStr;
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum CityStateType {
    Cultured,
    Maritime,
    Mercantile,
    Militaristic,
    Religious,
}

impl EnumStr for CityStateType {
    fn as_str(&self) -> &'static str {
        match self {
            CityStateType::Cultured => "Cultured",
            CityStateType::Maritime => "Maritime",
            CityStateType::Mercantile => "Mercantile",
            CityStateType::Militaristic => "Militaristic",
            CityStateType::Religious => "Religious",
        }
    }

    fn from_str(s: &str) -> Self {
        match s {
            "Cultured" => CityStateType::Cultured,
            "Maritime" => CityStateType::Maritime,
            "Mercantile" => CityStateType::Mercantile,
            "Militaristic" => CityStateType::Militaristic,
            "Religious" => CityStateType::Religious,
            _ => panic!("Invalid value for {}: {{}}", s),
        }
    }
}
