// Auto-generated by build.rs, DO NOT EDIT
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum Difficulty {
    Settler,
    Chieftain,
    Warlord,
    Prince,
    King,
    Emperor,
    Immortal,
    Deity,
}

impl Difficulty {
    pub fn as_str(&self) -> &'static str {
        match self {
            Difficulty::Settler => "Settler",
            Difficulty::Chieftain => "Chieftain",
            Difficulty::Warlord => "Warlord",
            Difficulty::Prince => "Prince",
            Difficulty::King => "King",
            Difficulty::Emperor => "Emperor",
            Difficulty::Immortal => "Immortal",
            Difficulty::Deity => "Deity",
        }
    }
}
