// Auto-generated by build.rs, DO NOT EDIT
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum Era {
    AncientEra,
    ClassicalEra,
    MedievalEra,
    RenaissanceEra,
    IndustrialEra,
    ModernEra,
    AtomicEra,
    InformationEra,
    FutureEra,
}

impl Era {
    pub fn as_str(&self) -> &'static str {
        match self {
            Era::AncientEra => "Ancient era",
            Era::ClassicalEra => "Classical era",
            Era::MedievalEra => "Medieval era",
            Era::RenaissanceEra => "Renaissance era",
            Era::IndustrialEra => "Industrial era",
            Era::ModernEra => "Modern era",
            Era::AtomicEra => "Atomic era",
            Era::InformationEra => "Information era",
            Era::FutureEra => "Future era",
        }
    }
}
