// Auto-generated by build.rs, DO NOT EDIT
use super::EnumStr;
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum TerrainType {
    Water,
    Flatland,
    Hill,
    Mountain,
}

impl EnumStr for TerrainType {
    fn as_str(&self) -> &'static str {
        match self {
            TerrainType::Water => "Water",
            TerrainType::Flatland => "Flatland",
            TerrainType::Hill => "Hill",
            TerrainType::Mountain => "Mountain",
        }
    }

    fn from_str(s: &str) -> Self {
        match s {
            "Water" => TerrainType::Water,
            "Flatland" => TerrainType::Flatland,
            "Hill" => TerrainType::Hill,
            "Mountain" => TerrainType::Mountain,
            _ => panic!("Invalid value for {}: {{}}", s),
        }
    }
}
