// Auto-generated by build.rs, DO NOT EDIT
use super::EnumStr;
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum UnitType {
    Civilian,
    Sword,
    Gunpowder,
    Archery,
    RangedGunpowder,
    Scout,
    Mounted,
    Armored,
    Siege,
    CivilianWater,
    MeleeWater,
    RangedWater,
    Submarine,
    AircraftCarrier,
    Fighter,
    Bomber,
    AtomicBomber,
    Missile,
    Helicopter,
}

impl EnumStr for UnitType {
    fn as_str(&self) -> &'static str {
        match self {
            UnitType::Civilian => "Civilian",
            UnitType::Sword => "Sword",
            UnitType::Gunpowder => "Gunpowder",
            UnitType::Archery => "Archery",
            UnitType::RangedGunpowder => "Ranged Gunpowder",
            UnitType::Scout => "Scout",
            UnitType::Mounted => "Mounted",
            UnitType::Armored => "Armored",
            UnitType::Siege => "Siege",
            UnitType::CivilianWater => "Civilian Water",
            UnitType::MeleeWater => "Melee Water",
            UnitType::RangedWater => "Ranged Water",
            UnitType::Submarine => "Submarine",
            UnitType::AircraftCarrier => "Aircraft Carrier",
            UnitType::Fighter => "Fighter",
            UnitType::Bomber => "Bomber",
            UnitType::AtomicBomber => "Atomic Bomber",
            UnitType::Missile => "Missile",
            UnitType::Helicopter => "Helicopter",
        }
    }

    fn from_str(s: &str) -> Self {
        match s {
            "Civilian" => UnitType::Civilian,
            "Sword" => UnitType::Sword,
            "Gunpowder" => UnitType::Gunpowder,
            "Archery" => UnitType::Archery,
            "Ranged Gunpowder" => UnitType::RangedGunpowder,
            "Scout" => UnitType::Scout,
            "Mounted" => UnitType::Mounted,
            "Armored" => UnitType::Armored,
            "Siege" => UnitType::Siege,
            "Civilian Water" => UnitType::CivilianWater,
            "Melee Water" => UnitType::MeleeWater,
            "Ranged Water" => UnitType::RangedWater,
            "Submarine" => UnitType::Submarine,
            "Aircraft Carrier" => UnitType::AircraftCarrier,
            "Fighter" => UnitType::Fighter,
            "Bomber" => UnitType::Bomber,
            "Atomic Bomber" => UnitType::AtomicBomber,
            "Missile" => UnitType::Missile,
            "Helicopter" => UnitType::Helicopter,
            _ => panic!("Invalid value for {}: {{}}", s),
        }
    }
}
