// Auto-generated by build.rs, DO NOT EDIT
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum UnitType {
    Civilian,
    Sword,
    Gunpowder,
    Archery,
    RangedGunpowder,
    Scout,
    Mounted,
    Armored,
    Siege,
    CivilianWater,
    MeleeWater,
    RangedWater,
    Submarine,
    AircraftCarrier,
    Fighter,
    Bomber,
    AtomicBomber,
    Missile,
    Helicopter,
}

impl UnitType {
    pub fn as_str(&self) -> &'static str {
        match self {
            UnitType::Civilian => "Civilian",
            UnitType::Sword => "Sword",
            UnitType::Gunpowder => "Gunpowder",
            UnitType::Archery => "Archery",
            UnitType::RangedGunpowder => "Ranged Gunpowder",
            UnitType::Scout => "Scout",
            UnitType::Mounted => "Mounted",
            UnitType::Armored => "Armored",
            UnitType::Siege => "Siege",
            UnitType::CivilianWater => "Civilian Water",
            UnitType::MeleeWater => "Melee Water",
            UnitType::RangedWater => "Ranged Water",
            UnitType::Submarine => "Submarine",
            UnitType::AircraftCarrier => "Aircraft Carrier",
            UnitType::Fighter => "Fighter",
            UnitType::Bomber => "Bomber",
            UnitType::AtomicBomber => "Atomic Bomber",
            UnitType::Missile => "Missile",
            UnitType::Helicopter => "Helicopter",
        }
    }
}
