// Auto-generated by build.rs, DO NOT EDIT
use super::EnumStr;
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum VictoryType {
    Scientific,
    Cultural,
    Domination,
    Diplomatic,
    Time,
    Neutral,
}

impl EnumStr for VictoryType {
    fn as_str(&self) -> &'static str {
        match self {
            VictoryType::Scientific => "Scientific",
            VictoryType::Cultural => "Cultural",
            VictoryType::Domination => "Domination",
            VictoryType::Diplomatic => "Diplomatic",
            VictoryType::Time => "Time",
            VictoryType::Neutral => "Neutral",
        }
    }

    fn from_str(s: &str) -> Self {
        match s {
            "Scientific" => VictoryType::Scientific,
            "Cultural" => VictoryType::Cultural,
            "Domination" => VictoryType::Domination,
            "Diplomatic" => VictoryType::Diplomatic,
            "Time" => VictoryType::Time,
            "Neutral" => VictoryType::Neutral,
            _ => panic!("Invalid value for {}: {{}}", s),
        }
    }
}
