mod add_features;
mod add_rivers;
pub mod assign_starting_tile;
mod generate_area_id;
mod generate_coasts;
mod generate_lakes;
mod generate_natural_wonders;
pub mod generate_regions;
mod generate_terrain;
mod generate_terrain_types;
mod place_bonus_resources;
mod place_city_states;
mod place_luxury_resources;
mod place_strategic_resources;
