mod add_features;
mod add_rivers;
pub mod assign_starting_tile;
mod balance_and_assign_civilization_starting_tiles;
mod choose_civilization_starting_tiles;
mod generate_area_ids;
mod generate_base_terrains;
mod generate_lakes;
mod generate_natural_wonders;
pub mod generate_regions;
mod generate_terrain_types;
mod place_bonus_resources;
mod place_city_states;
mod place_luxury_resources;
mod place_strategic_resources;
