// Auto-generated by build.rs, DO NOT EDIT
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum Feature {
    Forest,
    Jungle,
    Marsh,
    Fallout,
    Oasis,
    Floodplain,
    Ice,
    Atoll,
}

impl Feature {
    pub fn as_str(&self) -> &'static str {
        match self {
            Feature::Forest => "Forest",
            Feature::Jungle => "Jungle",
            Feature::Marsh => "Marsh",
            Feature::Fallout => "Fallout",
            Feature::Oasis => "Oasis",
            Feature::Floodplain => "Floodplain",
            Feature::Ice => "Ice",
            Feature::Atoll => "Atoll",
        }
    }
}
