// Auto-generated by build.rs, DO NOT EDIT
use enum_map::Enum;
use serde::{Deserialize, Serialize};

#[derive(Enum, PartialEq, Eq, Clone, Copy, Hash, Serialize, Deserialize, Debug)]
pub enum TerrainType {
    Water,
    Flatland,
    Hill,
    Mountain,
}

impl TerrainType {
    pub fn as_str(&self) -> &'static str {
        match self {
            TerrainType::Water => "Water",
            TerrainType::Flatland => "Flatland",
            TerrainType::Hill => "Hill",
            TerrainType::Mountain => "Mountain",
        }
    }
}
