[package]
name = "civ_map_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = { version = "0.15", optional = true, features = ["serde"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
regex = "1.10"
once_cell = "1.19"
rand = "0.8"
image = "0.25"
glam = "0.27"

[features]
default = ["use-hashbrown"]
use-hashbrown = ["hashbrown"]
